Repository boostcampwm-2024/web34-LearnDocker, pull requests merged in 2024-12, with the labels that each got.

#326 README에 기술적 도전 추가, 페이지 사진 최신화, 명령어 흐름도 추가
  README.md
Labels: docs

#327 탭 닫혔을 시 세션 해제 및 호스트 컨테이너 삭제 기능
  backend/src/app.module.ts
  backend/src/common/cache/cache.service.ts
  backend/src/common/constant.ts
  backend/src/common/request/request.interceptor.ts
  backend/src/common/request/request.module.ts
  backend/src/sandbox/sandbox.controller.ts
  frontend/src/App.tsx
  frontend/src/api/quiz.ts
Labels: BE, feature, refactor

#329 퀴즈 새로고침시 받아오는 버그, 가로줄 버그 수정, favicon 추가
  frontend/index.html
  frontend/src/api/quiz.ts
  frontend/src/assets/favicon.ico
  frontend/src/components/staticpages/DockerContainerPage.tsx
  frontend/src/components/staticpages/DockerImagePage.tsx
  frontend/src/components/visualization/ContainerNode.tsx
Labels: bug, FE

#330 docs: readme 업데이트
  README.md
Labels: docs

#328 랜딩 페이지 구현
  frontend/src/App.tsx
  frontend/src/assets/quiz-page-red-box.png
  frontend/src/assets/visualization-demo.gif
  frontend/src/components/Sidebar.tsx
  frontend/src/components/StartButton.tsx
  frontend/src/components/staticpages/LandingPage.tsx
Labels: FE

#332 nginx 설정을 적용하기 위해 trust proxy를 true로 추가
  backend/src/main.ts
Labels: BE, feature, env

#333 컨테이너 실행 및 중지 커스텀 이미지 수정, 로그 퀴즈 추가, 커맨드 유효성 검사 추가
  backend/src/quiz/quiz.service.ts
  backend/src/sandbox/pipes/command.pipe.spec.ts
  backend/src/sandbox/pipes/command.pipe.ts
  frontend/src/components/Sidebar.tsx
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizPageWrapper.tsx
  frontend/src/constant/quiz.ts
  sandbox/quiz-images/joke/joke.c
Labels: BE, FE, feature

#331 타이머 동작 기능 추가
  frontend/src/App.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/StartButton.tsx
  frontend/src/components/StopButton.tsx
  frontend/src/components/Timer.tsx
  frontend/src/components/TimerArea.tsx
  frontend/src/components/modals/TimerModal.tsx
  frontend/src/components/staticpages/DockerContainerLifeCyclePage.tsx
  frontend/src/components/staticpages/DockerContainerPage.tsx
  frontend/src/components/staticpages/DockerPage.tsx
Labels: FE, feature

#337 xterm 명령창 에러문 개선, 복붙 기능 구현
  backend/src/common/exception/filters.ts
  frontend/package.json
  frontend/src/api/quiz.ts
  frontend/src/components/quiz/XTerminal.tsx
  frontend/src/hooks/useTerminal.ts
  frontend/src/utils/terminalUtils.ts
Labels: BE, FE, feature

#336 input 창과 버튼 정렬, 숨겨진 힌트를 드러내는 버튼 추가, input창 위치를 언급하는 설명 추가
  backend/src/quiz/quiz.entity.ts
  backend/src/quiz/quiz.service.ts
  frontend/src/App.tsx
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizDescription.tsx
  frontend/src/components/quiz/QuizInputBox.tsx
  frontend/src/components/quiz/QuizNodes.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/QuizSubmitArea.tsx
  frontend/src/components/quiz/XTerminal.tsx
  frontend/src/components/staticpages/LandingPage.tsx
  frontend/src/components/visualization/DockerVisualization.tsx
  frontend/src/hooks/useQuizData.ts
  frontend/src/types/quiz.ts
  frontend/src/utils/terminalUtils.ts
Labels: BE, FE, feature, refactor

#335 에러페이지가 alert창과 같이 뜨는 현상 해결
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.service.ts
  backend/src/users/user.entity.ts
  backend/src/users/users.controller.spec.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  frontend/src/App.tsx
  frontend/src/components/ErrorPage.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/QuizPageWrapper.tsx
  frontend/src/components/quiz/VisualizationNodes.tsx
  frontend/src/hooks/useHostStatus.ts
Labels: bug, BE, FE, refactor

#334 Sidebar개선 및 hover에 대한 동작들 추가
  frontend/src/App.tsx
  frontend/src/components/PageInfoArea.tsx
  frontend/src/components/PageType.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/StartButton.tsx
  frontend/src/components/StopButton.tsx
  frontend/src/components/popover/ContainerPopover.tsx
  frontend/src/components/popover/ImagePopover.tsx
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizNodes.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/QuizSubmitArea.tsx
  frontend/src/components/visualization/ContainerNode.tsx
  frontend/src/constant/sidebarStatus.ts
  frontend/src/hooks/useSidebar.ts
  frontend/src/types/sidebar.ts
  frontend/src/utils/sidebarUtils.ts
Labels: FE, feature, refactor

#341 정적 페이지 렌더링 오류, 퀴즈 설명 수정, 터미널 반응형 최적화
  backend/src/quiz/quiz.service.ts
  frontend/src/App.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/QuizPageWrapper.tsx
  frontend/src/components/quiz/XTerminal.tsx
  frontend/src/components/staticpages/DockerContainerLifeCyclePage.tsx
  frontend/src/utils/terminalUtils.ts
Labels: bug, FE

#340 ImageId로부터 docker run 시 색상 입혀지지 않는 버그 해결
  frontend/src/App.tsx
  frontend/src/components/StopButton.tsx
  frontend/src/components/popover/ImagePopover.tsx
  frontend/src/components/visualization/ContainerNode.tsx
  frontend/src/constant/visualization.ts
  frontend/src/handlers/handler.ts
  frontend/src/utils/visualizationUtils.ts
Labels: bug, FE

#339 퀴즈 페이지 간 이동 시에도 터미널이 clear되는 현상 해결
  backend/src/sandbox/sandbox.service.ts
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizNodes.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/QuizPageWrapper.tsx
  frontend/src/components/quiz/QuizSubmitArea.tsx
Labels: BE, FE, refactor

#345 polling 방식으로 hostStatus를 업데이트
  frontend/src/hooks/useHostStatus.ts
Labels: bug, FE

#342 V체크표시 오류 수정
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/hooks/useSidebar.ts
Labels: bug, FE

#344 fix: imageName으로만 채점되는 버그 수정
  backend/src/quiz/quiz.service.ts
Labels: bug

#343 fix: 반응형 터미널 적용 시 투명한 터미널 영역이 삐져나오는 상황
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/utils/terminalUtils.ts
Labels: bug, FE

#346 문제 설명 추가, 사용하지 않는 코드 삭제
  backend/src/quiz/quiz.service.ts
  backend/src/sandbox/sandbox.controller.spec.ts
  backend/src/sandbox/sandbox.service.ts
  frontend/src/types/visualization.ts
Labels: refactor
