Repository boostcampwm-2024/web34-LearnDocker, pull requests merged in 2024-11, with the labels that each got.

#147 env: 프론트 개발환경 세팅
  .eslintrc.js
  eslint.config.mjs
  frontend/index.html
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  package-lock.json
  package.json
Labels: env

#154 /경로 요청 시 index.html파일 내리기
  .gitignore
  backend/.gitignore
  backend/package.json
  backend/public/test.html
  backend/src/app.module.ts
  package-lock.json
Labels: BE, feature

#152 헤더 컴포넌트 및 랜딩 페이지 내용 추가
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/assets/logo.png
  frontend/src/components/Header.tsx
  frontend/src/components/LandingPage.tsx
Labels: FE, feature

#157 pnpm 마이그레이션과 eslint react rule 적용
  .gitignore
  eslint.config.mjs
  frontend/src/App.tsx
  package.json
  pnpm-workspace.yaml
Labels: FE, env

#169 exception filter 적용, winston 로거 추가
  backend/package.json
  backend/src/app.module.ts
  backend/src/common/exception/errors.ts
  backend/src/common/exception/filters.ts
  backend/src/common/logger/config.ts
  backend/src/main.ts
  backend/src/users/users.controller.ts
Labels: BE

#168 경로별 routing 적용 & 이미지 가져오기 페이지 레이아웃 일부 구현
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/dropDown.svg
  frontend/src/components/Header.tsx
  frontend/src/components/ImagePullPage.tsx
  frontend/src/components/LandingPage.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/main.tsx
Labels: FE, feature

#167 Feature #18#19 proxyserver process docker elements request
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/sandbox/sandbox.controller.spec.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.module.ts
  backend/src/sandbox/sandbox.service.spec.ts
  backend/src/sandbox/sandbox.service.ts
Labels: BE, feature

#170 사용자 명령어 유효성 검증 및 exec를 통한 docker 요청 구현
  backend/package.json
  backend/src/app.controller.spec.ts
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/quiz/quiz.controller.spec.ts
  backend/src/quiz/quiz.controller.ts
  backend/src/quiz/quiz.entity.ts
  backend/src/quiz/quiz.module.ts
  backend/src/quiz/quiz.service.spec.ts
  backend/src/quiz/quiz.service.ts
  backend/src/sandbox/pipes/command.pipe.ts
  backend/src/sandbox/sandbox.controller.spec.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.module.ts
  backend/src/sandbox/sandbox.service.spec.ts
  backend/src/sandbox/sandbox.service.ts
  backend/tsconfig.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/dropDown.svg
  frontend/src/components/Header.tsx
  frontend/src/components/ImagePullPage.tsx
  frontend/src/components/LandingPage.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/main.tsx
Labels: BE, feature

#171 image 가져오기 페이지 문제 내용 및 시각화 데이터 요청
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/api/quiz.ts
  frontend/src/components/ErrorPage.tsx
  frontend/src/components/ImagePullPage.tsx
  frontend/src/types/quiz.ts
Labels: FE, feature

#172 시각화 뼈대 완성 및 이미지 관련 상태 변화 시각화 구현
  frontend/package.json
  frontend/src/components/BaseNode.tsx
  frontend/src/components/ContainerNode.tsx
  frontend/src/components/DockerVisualization.tsx
  frontend/src/components/ImagePullPage.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/types/types.ts
Labels: FE, feature

#177 학습 시작 API 구현
  .gitignore
  backend/package.json
  backend/src/app.module.ts
  backend/src/common/auth/auth.module.ts
  backend/src/common/auth/auth.service.ts
  backend/src/common/cache/cache.module.ts
  backend/src/common/cache/cache.service.ts
  backend/src/common/constant.ts
  backend/src/common/decorator/hide-in-prod.decorator.ts
  backend/src/common/exception/errors.ts
  backend/src/common/exception/filters.ts
  backend/src/main.ts
  backend/src/quiz/quiz.service.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.module.ts
  backend/src/sandbox/sandbox.service.ts
Labels: BE, feature

#176 이미지 관련 흐름 시각화 구현
  frontend/src/components/ImagePullPage.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/visualization/Arrow.tsx
  frontend/src/components/visualization/ArrowAnimation.tsx
  frontend/src/components/visualization/BaseNode.tsx
  frontend/src/components/visualization/ContainerNode.tsx
  frontend/src/components/visualization/DockerVisualization.tsx
  frontend/src/types/sidebar.ts
  frontend/src/types/types.ts
  frontend/src/types/visualization.ts
  frontend/tailwind.config.js
Labels: FE, feature

#175 프록시 서버에게 컨테이너 생성 요청 & 채점하기 요청 보내기
  README.md
  frontend/src/api/quiz.ts
  frontend/src/components/ImagePullPage.tsx
  frontend/src/components/StartButton.tsx
Labels: FE, feature

#174 데이터 가공 후 응답 및 사용자 명령요청 및 응답하기
  backend/src/sandbox/exec.api.ts
  backend/src/sandbox/pipes/command.pipe.spec.ts
  backend/src/sandbox/pipes/command.pipe.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.service.ts
  backend/src/sandbox/types/elements.ts
  backend/src/sandbox/utils.ts
Labels: BE, feature, refactor

#178 docs: Update README.md
  README.md
Labels: docs

#179 Backend Frontend IP주소 변경
  backend/src/sandbox/exec.api.ts
  backend/src/sandbox/sandbox.service.ts
  frontend/src/api/quiz.ts
  frontend/src/components/ImagePullPage.tsx
  package.json
Labels: env

#181 엔터 로직 구현, ImagePullPage 컴포넌트화, 상태 관리 로직 커스텀훅으로 분리
  frontend/index.html
  frontend/src/App.tsx
  frontend/src/api/quiz.ts
  frontend/src/components/ImagePullPage.tsx
  frontend/src/components/LandingPage.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizDescription.tsx
  frontend/src/components/quiz/QuizTextarea.tsx
  frontend/src/hooks/useDockerVisualization.ts
  frontend/src/hooks/useTerminalInput.ts
  frontend/src/types/quiz.ts
Labels: FE, feature, refactor

#182 개발 환경과 배포 환경변수 나누기
  .gitignore
  backend/package.json
  frontend/src/api/quiz.ts
  frontend/vite.config.ts
Labels: env

#185 axios api 요청 async/await 방식으로 변경
  frontend/src/api/quiz.ts
  frontend/src/components/ImagePullPage.tsx
  frontend/src/components/StartButton.tsx
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/hooks/useDockerVisualization.ts
  frontend/src/hooks/useTerminalInput.ts
  frontend/src/types/quiz.ts
  frontend/src/types/visualization.ts
Labels: FE, feature, refactor

#186 배포 시 nestjs 서버에 로그를 파일로 남기기
  backend/package.json
  backend/src/app.module.ts
  backend/src/common/decorator/hide-in-production.decorator.ts
  backend/src/common/exception/filters.ts
  backend/src/common/logger/config.ts
  backend/src/common/logger/middleware.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.service.ts
  package.json
Labels: BE, env

#224 학습 시작 버튼 누를 시 Timer생성 및 정적 페이지 라우팅 구현
  frontend/src/App.tsx
  frontend/src/api/timer.ts
  frontend/src/components/DockerContainerLifeCyclePage.tsx
  frontend/src/components/DockerContainerPage.tsx
  frontend/src/components/DockerImagePage.tsx
  frontend/src/components/DockerPage.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/StartButton.tsx
  frontend/src/components/Timer.tsx
  frontend/src/types/timer.ts
Labels: FE, feature

#225 서버 시작시 퀴즈 데이터 db 초기화 및 삽입
  backend/package.json
  backend/src/quiz/quiz.service.ts
Labels: BE, feature

#226 사용자 명령 입력창 개선
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.module.ts
  backend/src/sandbox/sandbox.service.ts
  frontend/src/components/quiz/QuizTextarea.tsx
  frontend/src/hooks/useTerminalInput.ts
Labels: BE, FE, refactor

#227 이미지 가져오기 퀴즈 채점 관련 백엔드 API 구현
  backend/src/common/auth/auth.guard.ts
  backend/src/common/auth/auth.module.ts
  backend/src/common/auth/auth.service.ts
  backend/src/common/cache/cache.service.ts
  backend/src/common/exception/filters.ts
  backend/src/common/types/request.ts
  backend/src/common/types/session.ts
  backend/src/quiz/quiz.controller.ts
  backend/src/quiz/quiz.module.ts
  backend/src/quiz/quiz.service.ts
  backend/src/sandbox/pipes/command.pipe.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.module.ts
  backend/src/sandbox/sandbox.service.ts
Labels: BE, feature

#230 사용자 image, container 시각화 정보 요청 API를 포트 매핑 방식으로 변경
  backend/src/common/types/session.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.service.ts
Labels: bug, BE, feature

#229 퀴즈 페이지들 구현
  frontend/src/App.tsx
  frontend/src/api/quiz.ts
  frontend/src/api/timer.ts
  frontend/src/components/DockerContainerLifeCyclePage.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/quiz/QuizInputBox.tsx
  frontend/src/components/quiz/QuizTextarea.tsx
  frontend/src/components/quizpages/InputBoxQuizPage.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
  frontend/src/components/staticpages/DockerContainerLifeCyclePage.tsx
  frontend/src/components/staticpages/DockerContainerPage.tsx
  frontend/src/components/staticpages/DockerImagePage.tsx
  frontend/src/components/staticpages/DockerPage.tsx
  frontend/src/components/staticpages/LandingPage.tsx
  frontend/src/components/visualization/ContainerNode.tsx
  frontend/src/types/timer.ts
Labels: FE, feature

#232 Sandbox상태 요청 및 visualization 개선
  frontend/src/components/quizpages/InputBoxQuizPage.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
  frontend/src/components/visualization/ContainerNode.tsx
  frontend/src/hooks/useDockerVisualization.ts
  frontend/src/types/visualization.ts
Labels: FE, feature

#233 stderr 나오도록 수정, quizTextarea를 xterm으로 교체
  backend/src/sandbox/exec.api.ts
  frontend/package.json
  frontend/src/api/quiz.ts
  frontend/src/components/quiz/QuizTextarea.tsx
  frontend/src/components/quiz/XTerminal.tsx
  frontend/src/components/quizpages/InputBoxQuizPage.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
  frontend/src/constant/xterm.ts
  frontend/src/hooks/useDockerVisualization.ts
  frontend/src/hooks/useTerminal.ts
  frontend/src/hooks/useTerminalInput.ts
  frontend/src/types/quiz.ts
  frontend/src/utils/terminalUtils.ts
Labels: bug, BE, FE, feature

#234 사용자 레벨에 따라 퀴즈 정보 제한 및 컨테이너 생성하기 채점 기능 구현
  backend/src/common/cache/cache.service.ts
  backend/src/common/exception/filters.ts
  backend/src/common/types/request.ts
  backend/src/common/types/session.ts
  backend/src/quiz/quiz.controller.ts
  backend/src/quiz/quiz.service.ts
  backend/src/sandbox/sandbox.service.ts
  frontend/src/api/quiz.ts
  frontend/src/components/quiz/QuizButtons.tsx
Labels: BE, FE, feature

#235 다음 버튼 눌러서 다음 퀴즈로 이동하기
  backend/src/quiz/quiz.controller.ts
  backend/src/quiz/quiz.service.ts
  frontend/src/api/quiz.ts
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quizpages/InputBoxQuizPage.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
Labels: FE, feature

#236 fix: 시각화 데이터 예외 처리 추가
  backend/src/sandbox/sandbox.service.ts
Labels: bug, BE

#237 리드미 업데이트
  README.md
Labels: docs

#243 컨테이너 실행하기 퀴즈 채점 기능 구현 및 QuizSubmitArea 컴포넌트 추가
  backend/src/common/cache/cache.service.ts
  backend/src/common/types/session.ts
  backend/src/quiz/quiz.controller.ts
  backend/src/quiz/quiz.module.ts
  backend/src/quiz/quiz.service.ts
  backend/src/sandbox/sandbox.service.ts
  frontend/src/api/quiz.ts
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizInputBox.tsx
  frontend/src/components/quiz/QuizSubmitArea.tsx
  frontend/src/components/quizpages/InputBoxQuizPage.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
  frontend/src/constant/quiz.ts
Labels: BE, FE, feature

#244 프론트엔드 개발 서버와 백엔드 개발 서버 한번에 띄우기
  backend/package.json
  frontend/src/api/quiz.ts
  frontend/src/api/timer.ts
  frontend/vite.config.ts
  package.json
Labels: env

#246 퀴즈 문제 구현, 퀴즈 2,3,6,7,8,9 채점 구현
  backend/src/quiz/quiz.service.ts
  frontend/src/components/quiz/QuizButtons.tsx
Labels: BE, FE, feature

#245 Docker Container및 Image시각화 구현 docker Container및 Image시각화 구현
  frontend/src/api/timer.ts
  frontend/src/components/quiz/XTerminal.tsx
  frontend/src/components/quizpages/InputBoxQuizPage.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
  frontend/src/components/visualization/ArrowAnimation.tsx
  frontend/src/components/visualization/ContainerNode.tsx
  frontend/src/constant/visualization.ts
  frontend/src/hooks/useDockerVisualization.ts
  frontend/src/hooks/useTerminal.ts
  frontend/src/types/visualization.ts
  frontend/src/utils/terminalUtils.ts
  frontend/src/utils/visualizationUtils.ts
  frontend/tailwind.config.js
Labels: FE, feature

#270 명령어 입력창 로딩 화면 구현 및 폴링 방식으로 호스트 컨테이너 상태 확인 기능 추가
  backend/src/sandbox/constant.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.service.ts
  frontend/src/api/quiz.ts
  frontend/src/components/quiz/XTerminal.tsx
  frontend/src/components/quizpages/InputBoxQuizPage.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
  frontend/src/constant/hostStatus.ts
  frontend/src/utils/LoadingTerminal.ts
  frontend/src/utils/terminalUtils.ts
Labels: BE, FE, feature

#271 다음 버튼 눌렀을 때 얼럿 구현, 제출 버튼 눌렀을 때 모달 구현
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/modals/QuizSubmitResultModal.tsx
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizSubmitArea.tsx
  frontend/src/components/quizpages/InputBoxQuizPage.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
  frontend/src/hooks/useAlert.ts
  frontend/src/types/quiz.ts
  frontend/tailwind.config.js
Labels: FE, feature

#269 refactor: 퀴즈 라우팅을 동적 파라미터 방식으로 변경
  frontend/src/App.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/QuizSubmitArea.tsx
  frontend/src/components/quizpages/TextAreaQuizPage.tsx
  frontend/src/components/visualization/DockerVisualization.tsx
  frontend/src/hooks/useDockerVisualization.ts
  frontend/src/hooks/useQuizData.ts
  frontend/src/types/visualization.ts
Labels: FE, refactor

#272 서버 리소스 관리를 위한 태스크 작업
  backend/src/common/auth/auth.service.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.service.ts
  backend/src/sandbox/utils.ts
  frontend/src/api/quiz.ts
  frontend/src/api/timer.ts
  frontend/src/components/Sidebar.tsx
  frontend/src/components/StartButton.tsx
  frontend/src/components/StopButton.tsx
  frontend/src/components/Timer.tsx
  frontend/src/components/TimerArea.tsx
Labels: BE, FE, feature

#274 터미널 관련 수정 사항 반영 및 SSE 방식 도입
  backend/src/sandbox/constant.ts
  backend/src/sandbox/sandbox.controller.ts
  frontend/index.html
  frontend/src/api/quiz.ts
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/hooks/useHostStatus.ts
  frontend/src/hooks/useTerminal.ts
  frontend/src/utils/LoadingTerminal.ts
  frontend/src/utils/terminalUtils.ts
Labels: BE, FE, feature, refactor

#275 퀴즈 페이지 리팩토링, 터미널 리사이징 이벤트 등록
  frontend/src/App.tsx
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizInputBox.tsx
  frontend/src/components/quiz/QuizNodes.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/QuizPageWrapper.tsx
  frontend/src/components/quiz/QuizSubmitArea.tsx
  frontend/src/components/quiz/VisualizationNodes.tsx
  frontend/src/components/quiz/XTerminal.tsx
  frontend/src/hooks/useQuizData.ts
  frontend/src/index.css
  frontend/src/utils/terminalUtils.ts
Labels: FE, feature, refactor

#276 사용자 연속 요청 block구현 및 세션 청소기 구현
  backend/package.json
  backend/src/app.module.ts
  backend/src/common/cache/cache.module.ts
  backend/src/common/cache/cache.service.ts
  backend/src/common/constant.ts
  backend/src/common/exception/errors.ts
  backend/src/common/exception/filters.ts
  backend/src/common/request/request.guard.ts
  backend/src/common/request/request.module.ts
  backend/src/common/request/request.service.ts
  backend/src/common/types/session.ts
  backend/src/sandbox/sandbox.controller.ts
  backend/src/sandbox/sandbox.service.ts
  frontend/src/api/quiz.ts
  frontend/src/components/StartButton.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/VisualizationNodes.tsx
  frontend/src/components/quiz/XTerminal.tsx
  frontend/src/hooks/useTerminal.ts
  frontend/src/utils/terminalUtils.ts
Labels: BE, FE, feature

#278 레지스트리 세팅, 퀴즈 이미지 준비, 볼륨 마운트 못하게 막기
  backend/src/quiz/quiz.service.ts
  backend/src/sandbox/pipes/command.pipe.ts
  backend/src/sandbox/sandbox.service.ts
  sandbox/host-container/Dockerfile
  sandbox/host-container/docker-compose.yml
  sandbox/quiz-images/hello-world/Dockerfile
  sandbox/quiz-images/hello-world/hello.c
  sandbox/quiz-images/joke/Dockerfile
  sandbox/quiz-images/joke/joke.c
  sandbox/registry/docker-compose.yml
  sandbox/setup.ps1
  sandbox/setup.sh
Labels: BE, env

#277 eventSource 동작 개선 및 "Docker란?", "Docker Image란?" 정적 페이지 구성
  frontend/src/App.tsx
  frontend/src/components/quiz/QuizPage.tsx
  frontend/src/components/quiz/VisualizationNodes.tsx
  frontend/src/components/staticpages/DockerImagePage.tsx
  frontend/src/components/staticpages/DockerPage.tsx
  frontend/src/hooks/useHostStatus.ts
Labels: FE, feature

#279 컨테이너 생명주기 설명 및 그림 추가, requestQuizData api react query 도입
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/containerLifeCycle.png
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizNodes.tsx
  frontend/src/components/quiz/QuizPageWrapper.tsx
  frontend/src/components/staticpages/DockerContainerLifeCyclePage.tsx
  frontend/src/hooks/useQuizData.ts
Labels: FE, feature

#280 alert 표시 개선 및 예외상황에서 터미널 입력 방지
  backend/src/common/exception/filters.ts
  frontend/src/api/quiz.ts
  frontend/src/components/quiz/QuizButtons.tsx
  frontend/src/components/quiz/QuizPageWrapper.tsx
  frontend/src/components/staticpages/DockerImagePage.tsx
  frontend/src/hooks/useTerminal.ts
  frontend/src/utils/terminalUtils.ts
Labels: FE, feature, refactor

#281 Container static page구현
  frontend/src/assets/docker-container.png
  frontend/src/components/staticpages/DockerContainerPage.tsx
Labels: FE

#282 typeorm column 자료형 변경, dind container에 --tsl=false 옵션 지정
  backend/src/quiz/quiz.entity.ts
  backend/src/sandbox/sandbox.service.ts
  sandbox/quiz-images/joke/joke.c
Labels: bug

#283 hotfix: 렌더링 안 되는 버그 수정
  frontend/src/components/quiz/QuizPageWrapper.tsx
Labels: bug
